### ISSUE TITLE
AskXammy feed fails

### ISSUE THREAD

**Issue by LeomarisReyes** [planetxamarin/planetxamarin#694]
**Describe the bug**
When I publish my post it doesn't appear on preview tabs, I was having problems with my RSS Feed SSL, but I fixed it.

- Related to: #691
- Link:  https://AskXammy.com/feed 
- RSS validator: https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2FAskXammy.com%2Ffeed

**Expected behavior**
Show my post after I published it.

**Screenshots**
![image](https://user-images.githubusercontent.com/35940594/94323200-e447a580-ff62-11ea-87aa-09919efed4bb.png)

**Comment by Cheesebaron** [comment]
It seems to be failing contacting your blog from where we host on Azure: https://www.planetxamarin.com/logs/detail?id=e933da71-f8aa-4113-9481-7f53a16f16dc

```
System.Exception: Leomaris Reyes's feed of https://askxammy.com/feed failed to load. ---> Firehose.Web.Infrastructure.FeedReadFailedException: Loading remote syndication feed failed ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 185.224.137.187:443
   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Firehose.Web.Infrastructure.NewCombinedFeedSource.<ReadFeed>d__13.MoveNext() in C:\GitHub\planetxamarin\src\Firehose.Web\Infrastructure\NewCombinedFeedSource.cs:line 115
   --- End of inner exception stack trace ---
   at Firehose.Web.Infrastructure.NewCombinedFeedSource.<ReadFeed>d__13.MoveNext() in C:\GitHub\planetxamarin\src\Firehose.Web\Infrastructure\NewCombinedFeedSource.cs:line 131
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Polly.Retry.AsyncRetryEngine.<ImplementationAsync>d__0`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Polly.AsyncPolicy.<ExecuteAsync>d__21`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Firehose.Web.Infrastructure.NewCombinedFeedSource.<TryReadFeed>d__12.MoveNext() in C:\GitHub\planetxamarin\src\Firehose.Web\Infrastructure\NewCombinedFeedSource.cs:line 100
   --- End of inner exception stack trace ---
```

It says, your host is actively rejecting the connection. Not sure which host you are using. Maybe they have some firewall rules in place that are rejecting us?
